export const message = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  DELETED: 'DELETED',
  DUPLICATE: 'DUPLICATE',
  INVALID: 'INVALID',
  NOT_ALLOWED: 'NOT_ALLOWED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_TYPE_NOT_FOUND: 'USER_TYPE_NOT_FOUND'
};

